language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t kkomninos/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kkomninos/docker-react npm run test

deploy:
  provider: elastikbeanstalk
  region: "us-west-2"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-078441829787"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"